[package]
name = "multi-readers"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "Multiple Readers"
keywords = ["readers", "multiple", "multi", "bytes-reader"]
repository = "https://github.com/Pesju13/multi-readers.git"
[dependencies]




