[package]
name = "multi-readers"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "Multiple Readers for sync and async"
keywords = ["readers", "multiple", "async", "bytes-reader"]
repository = "https://github.com/Pesju13/multi-readers.git"
[dependencies]

tokio = { version = "1.37.0", optional = true }

[features]
async = ["tokio"]
